### ISSUE TITLE
Deploying a model after training with kedro-sagemaker

### ISSUE THREAD

**Issue by Riezebos** [getindata/kedro-sagemaker#15]
Hi,

Thanks for this cool project! I would like to integrate Kedro with Sagemaker. If I understand things correctly, using `kedro-sagemaker` I can run a Kedro Pipeline in Sagemaker Pipelines. This would result in a trained model that I can deploy as a Sagemaker Endpoint for inference. 

When the deployed model receives a request, the data still needs to be transformed (e.g. scaling, one-hot encoding, ...). Is there a way to run the Kedro Pipeline as part of the Sagemaker Endpoint using transformations that are fitted during training?

**Comment by Riezebos** [comment]
Thanks for the quick response, those seem like good options! Do you know whether there are any plugins/integrations between Kedro -> Sagemaker Model Registry -> BentoML?

It seems straightforward to store the processing steps+model in s3 using BentoML inside of a Kedro Node, but it would be nice to use the Sagemaker Model Registry for governance

**Comment by marrrcin** [comment]
I'm not aware of those, however I haven't searched.
